ApplicationMVC/Models/Categoria.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApplicationMVC.Models
{
    [Table("G2_CATEGORIAS")]
    public class Categoria
    {
        [Key]
        [Column("ID_CATEGORIA")]
        public Guid CategoriaId { get; set; }

        [Required(ErrorMessage = "Informe o nome da categoria")]
        [StringLength(100, ErrorMessage = "O tamanho máximo é {1} caracteres")]
        [Display(Name = "Nome da Categoria")]
        [Column("NM_CATEGORIA")]
        public string NomeCategoria { get; set; }

        [Required(ErrorMessage = "Informe a descrição da categoria")]
        [StringLength(200, ErrorMessage = "O tamanho máximo é {1} caracteres")]
        [Display(Name = "Descrição da Categoria")]
        [Column("DS_CATEGORIA")]
        public string DescricaoCategoria { get; set; }

        public List<Roupa> Roupas { get; set; }
    }
}

ApplicationMVC/Models/ErrorViewModel.cs
namespace ApplicationMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ApplicationMVC/Models/Roupa.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApplicationMVC.Models
{
    [Table("G2_ROUPAS")]
    public class Roupa
    {
        [Key]
        [Column("ID_ROUPA")]
        public Guid RoupaId { get; set; }

        [Required(ErrorMessage = "Informe o nome da roupa")]
        [StringLength(80, MinimumLength = 10, ErrorMessage = "O {0} deve ter no mínimo {1} e no máximo {2} caracteres")]
        [Display(Name = "Nome da Roupa")]
        [Column("NM_ROUPA")]
        public string NomeRoupa { get; set; }

        [Required(ErrorMessage = "Informe a descrição da roupa")]
        [MinLength(20, ErrorMessage = "Descrção deve ter no mínimo {1} caracteres")]
        [MaxLength(200, ErrorMessage = "Descrção deve ter no máximo {1} caracteres")]
        [Display(Name = "Nome da Roupa")]
        [Column("DS_ROUPA")]
        public string DescricaoRoupa { get; set; }

        [Required(ErrorMessage = "Informe o preço da roupa")]
        [Display(Name = "Preço")]
        [Range(1,999.99, ErrorMessage = "O preço deve estar entre {1} e {2}")]
        [Column("VL_ROUPA", TypeName = "decimal(10,2)")]
        public double PrecoRoupa { get; set; }

        [Display(Name = "Caminho da Imagem Normal")]
        [StringLength(200, ErrorMessage = "O {0} deve ter no máximo {1} caracteres")]
        [Column("FL_IMAGEM_ROUPA")]
        public string ImagemUrl { get; set; }

        [Display(Name = "Caminho da Imagem Normal")]
        [StringLength(200, ErrorMessage = "O {0} deve ter no máximo {1} caracteres")]
        [Column("FL_THUMBNAIL_ROUPA")]
        public string ThumbnailUrl { get; set; }

        [Display(Name = "Estoque")]
        [Column("FL_ESTOQUE")]
        public bool EmEstoque { get; set; }

        [ForeignKey("G2_CATEGORIAS")]
        [Column("ID_CATEGORIA")]
        public Guid CategoriaId { get; set; }

        public virtual Categoria Categoria { get; set; }
    }
}

ApplicationMVC/ViewModels/RoupaListViewModel.cs
using ApplicationMVC.Models;

namespace ApplicationMVC.ViewModels
{
    public class RoupaListViewModel
    {
        public IEnumerable<Roupa> Roupas { get; set; }
        public string CategoriaAtual { get; set; }
    }
}

ApplicationMVC/Controllers/HomeController.cs
using System.Diagnostics;
using ApplicationMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace ApplicationMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ApplicationMVC/Controllers/RoupaController.cs
using ApplicationMVC.Repositories.Interfaces;
using ApplicationMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ApplicationMVC.Controllers
{
    public class RoupaController : Controller
    {
        private readonly IRoupaRepository _roupaRepository;

        public RoupaController(IRoupaRepository roupaRepository)
        {
            _roupaRepository = roupaRepository;
        }

        public IActionResult List()
        {
            //var roupas = _roupaRepository.Roupas;
            //return View(roupas);

            var roupasListViewModel = new RoupaListViewModel();
            roupasListViewModel.Roupas = _roupaRepository.Roupas;
            roupasListViewModel.CategoriaAtual = "Categoria Atual";
            return View(roupasListViewModel);
        }
    }
}

ApplicationMVC/Views/Home/Index.cshtml
<partial name="_Carrossel" />

ApplicationMVC/Views/Roupa/List.cshtml
@model RoupaListViewModel

<div>
    <h1 align="center">@Model.CategoriaAtual</h1>
</div>

<hr />
<br />

<div class="container">
    <div class="row">
        @foreach (var roupa in Model.Roupas)
        {
            <div align="center" class="col-sm-4 col-md-4 col-lg-4">
                <h4>@roupa.NomeRoupa</h4>
                <p><img src="@roupa.ImagemUrl" class="img-fluid" width="200" /></p>
                <h5>Preço: @roupa.PrecoRoupa.ToString("c")</h5>
                <h6>@roupa.DescricaoRoupa</h6>
            </div>
        }
    </div>
</div>

ApplicationMVC/Views/Shared/_Carrossel.cshtml
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/img1.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/images/img2.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/images/img3.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

ApplicationMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApplicationMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ApplicationMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ApplicationMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roupa" asp-action="List">Roupas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ApplicationMVC
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>